[package]
name = "cronus-lang"
version = "0.1.0"
edition = "2021"
description = "Compile full-stack software from a single spec file"
license = "MIT"
repository = "https://github.com/cooud/cronus"
readme = "README.md"
keywords = ["language", "full-stack", "compiler", "ssr", "database"]
categories = ["command-line-utilities", "web-programming", "development-tools"]

[[bin]]
name = "cronus"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
bytes = "1"
jsonwebtoken = "9"
argon2 = { version = "0.5", features = ["rand"] }
rand_core = { version = "0.6", features = ["getrandom"] }
async-stream = "0.3"
tokio-stream = "0.1"
futures-core = "0.3"

[profile.release]
opt-level = 3
lto = true
strip = true
