pub fn print_help() {
    println!("\x1b[36m\x1b[1m");
    println!("  ██████╗██████╗  ██████╗ ███╗   ██╗██╗   ██╗███████╗");
    println!(" ██╔════╝██╔══██╗██╔═══██╗████╗  ██║██║   ██║██╔════╝");
    println!(" ██║     ██████╔╝██║   ██║██╔██╗ ██║██║   ██║███████╗");
    println!(" ██║     ██╔══██╗██║   ██║██║╚██╗██║██║   ██║╚════██║");
    println!(" ╚██████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╔╝███████║");
    println!("  ╚═════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝ ╚══════╝");
    println!("\x1b[0m");
    println!("  \x1b[90mThe Cognitive Runtime v0.1.0 (Rust native)\x1b[0m\n");
    println!("  \x1b[1mUsage:\x1b[0m cronus <command> [options]\n");
    println!("  \x1b[1mCommands:\x1b[0m");
    println!("    \x1b[32mrun\x1b[0m [port] [--strict] [--audit-canvas [port]]  Parse .cronus → serve");
    println!("          --audit-canvas: bind 127.0.0.1, exclusive /audit/* path (default port 5176)");
    println!("    \x1b[32mdebug\x1b[0m [port]           Run with request tracing, colored logs, /api/debug/traces");
    println!("    \x1b[32mnew\x1b[0m <template>       Create project (landing/admin/saas/api/ecommerce/blog)");
    println!("    \x1b[32mseed\x1b[0m [count]          Seed database with fake data (default: 10 rows)");
    println!("    \x1b[32mbuild\x1b[0m [--strict] [--strict-ai] [--ai|--machine|--json-errors]  Validate .cronus file");
    println!("          --ai / --machine / --json-errors: AI-Error Protocol (structured JSON with fix hints)");
    println!("    \x1b[32mparse\x1b[0m <file> [--strict] Parse and show AST (strict mode)");
    println!("    \x1b[32mdeploy\x1b[0m           Generate deploy artifacts (--fly, --railway, --static)");
    println!("    \x1b[32mdoctor\x1b[0m           Check .cronus syntax + DB + ports");
    println!("    \x1b[32mstats\x1b[0m            Project stats (entities, pages, DB size)");
    println!("    \x1b[32mexport\x1b[0m           Export to cronus-project.ir.json");
    println!("    \x1b[32mtest\x1b[0m [port]          Auto-gen and run CRUD tests");
    println!("    \x1b[32mtest\x1b[0m --conformance   Run conformance test suite");
    println!("    \x1b[32mcompose\x1b[0m          Compose all .cronus files and show result");
    println!("    \x1b[32mgenerate\x1b[0m <desc>  Generate .cronus from description");
    println!("    \x1b[32mvalidate\x1b[0m [file] [--json] [--strict-ai]  Validate (--strict-ai: all warnings = errors, JSON output)");
    println!("    \x1b[32mvalidate\x1b[0m --mission       Validate code against constitution + objective");
    println!("    \x1b[32mbrief\x1b[0m            Generate AI context capsule (~500 words)");
    println!("    \x1b[32msync\x1b[0m             Generate .cronus/state-digest.json from project state");
    println!("    \x1b[32mhandoff\x1b[0m          Complete active task, update state digest for next session");
    println!("    \x1b[32mlease\x1b[0m check|list|create  Task lease management (drift detection)");
    println!("    \x1b[32mdrift\x1b[0m [--explain]    Detect strategic, scope, and semantic drift");
    println!("    \x1b[32mspec\x1b[0m <validate|list|codegen> Validate, list, or generate from .spec.toml files");
    println!("    \x1b[32msegment\x1b[0m <create|list|show|check>  Semantic block isolation (parallel agents)");
    println!("    \x1b[32mreconcile\x1b[0m <a> <b> [--output <file>]  AST-level merge of two .cronus files");
    println!("    \x1b[32mreview\x1b[0m [task-id]    Semantic review of task changes (what changed, not diff)");
    println!("    \x1b[32mtimeline\x1b[0m         Task-based project history (newest first)");
    println!("    \x1b[32mstatus\x1b[0m           Semantic project overview (like git status for CRONUS)");
    println!("    \x1b[32mmemory\x1b[0m sessions|decisions|log|decide  Semantic memory across sessions");
    println!("    \x1b[32mverify-audit\x1b[0m     Verify audit trail hash chain integrity");
    println!("    \x1b[32maudit\x1b[0m language|logic|visual|all|legacy   Cronus Audit (legacy = dump-text HTML)");
    println!("    \x1b[32mversion\x1b[0m          Show version");
    println!();
}
