#![allow(dead_code, unused_imports, unused_variables)]
use std::collections::HashMap;
use super::detect::{SectionBlueprint, ItemBlueprint};

// ---------------------------------------------------------------------------
// CronusFile — top-level representation of a .cronus source file
// ---------------------------------------------------------------------------

pub struct CronusFile {
  pub app_name: String,
  pub port: u16,
  pub theme: String,
  pub style_config: HashMap<String, String>,
  pub sections: Vec<SectionBlueprint>,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Returns `level` repetitions of two-space indentation.
fn indent(level: usize) -> String {
  "  ".repeat(level)
}

/// Escapes double-quotes inside a string so it can be safely wrapped in `"…"`.
fn escape_cronus(s: &str) -> String {
  s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Structural config keys that belong on the section opening line.
const STRUCTURAL_KEYS: &[&str] = &["cols", "style", "span", "gap", "layout"];

/// Common Material icon names that may leak into CTA text.
const ICON_NAMES: &[&str] = &[
  "arrow_forward", "arrow_back", "arrow_upward", "arrow_downward",
  "add", "remove", "close", "check", "search", "menu", "home",
  "settings", "delete", "edit", "share", "send", "download",
  "upload", "refresh", "more_vert", "more_horiz", "chevron_right",
  "chevron_left", "expand_more", "expand_less", "open_in_new",
  "content_copy", "visibility", "favorite", "star", "info",
  "warning", "error", "help", "launch", "link", "east", "west",
  "north", "south", "trending_up", "trending_down", "bolt",
  "rocket_launch", "play_arrow", "pause", "stop",
];

/// Cleans text by trimming whitespace, removing trailing icon names,
/// and collapsing multiple spaces/newlines into a single space.
fn clean_text(s: &str) -> String {
  // Replace newlines and collapse whitespace
  let collapsed: String = s
    .split_whitespace()
    .collect::<Vec<_>>()
    .join(" ");

  // Remove trailing icon names
  let mut result = collapsed.trim().to_string();
  for icon in ICON_NAMES {
    if result.ends_with(icon) {
      result = result[..result.len() - icon.len()].trim().to_string();
    }
  }
  // Also strip leading icon names
  for icon in ICON_NAMES {
    if result.starts_with(icon) {
      result = result[icon.len()..].trim().to_string();
    }
  }
  result
}

/// Formats only structural config keys as inline `key:value` pairs for the section opening line.
/// Keys are sorted for deterministic output.
fn emit_structural_config(config: &HashMap<String, String>) -> String {
  let mut keys: Vec<&String> = config
    .keys()
    .filter(|k| STRUCTURAL_KEYS.contains(&k.as_str()))
    .collect();
  if keys.is_empty() {
    return String::new();
  }
  keys.sort();
  keys
    .iter()
    .map(|k| format!("{}:{}", k, config[*k]))
    .collect::<Vec<_>>()
    .join(" ")
}

/// Formats a `HashMap<String, String>` as inline `key:value` pairs.
/// Keys are sorted for deterministic output.
fn emit_config_pairs(config: &HashMap<String, String>) -> String {
  if config.is_empty() {
    return String::new();
  }
  let mut keys: Vec<&String> = config.keys().collect();
  keys.sort();
  keys
    .iter()
    .map(|k| {
      let v = &config[*k];
      if v.contains(':') || v.contains(' ') || v.contains('/') || v.contains('"') {
        format!("{}:\"{}\"", k, escape_cronus(v))
      } else {
        format!("{}:{}", k, v)
      }
    })
    .collect::<Vec<_>>()
    .join(" ")
}

/// Wraps `text` in double-quotes after escaping.
fn quoted(s: &str) -> String {
  format!("\"{}\"", escape_cronus(s))
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/// Generates a complete `.cronus` source file from a `CronusFile`.
pub fn emit_cronus(file: &CronusFile) -> String {
  let mut out = String::with_capacity(4096);

  // Header comment
  out.push_str("# Generated by cronus dump\n");
  out.push('\n');

  // app block
  out.push_str(&format!("app {} {{\n", quoted(&file.app_name)));
  out.push_str("  stack react + tailwind\n");
  out.push_str(&format!("  port {}\n", file.port));
  out.push_str("  database sqlite \"./data.db\"\n");
  out.push_str(&format!("  theme {}\n", file.theme));
  out.push_str("}\n\n");

  // style block
  out.push_str("style {\n");
  out.push_str(&format!("  theme {}\n", file.theme));
  if let Some(accent) = file.style_config.get("accent") {
    out.push_str(&format!("  accent {}\n", accent));
  }
  if let Some(font) = file.style_config.get("font") {
    out.push_str(&format!("  font {}\n", quoted(font)));
  }
  // Emit remaining style keys (sorted, skip already-emitted ones)
  let skip = ["accent", "font", "theme"];
  let mut extra_keys: Vec<&String> = file
    .style_config
    .keys()
    .filter(|k| !skip.contains(&k.as_str()))
    .collect();
  extra_keys.sort();
  for k in extra_keys {
    out.push_str(&format!("  {} {}\n", k, quoted(&file.style_config[k])));
  }
  out.push_str("}\n\n");

  // page block wrapping all sections
  out.push_str("page \"/\" type:custom {\n");
  for bp in &file.sections {
    out.push_str(&emit_section(bp, 1));
    out.push('\n');
  }
  out.push_str("}\n");

  out
}

// ---------------------------------------------------------------------------
// Section emitter — dispatches by section_type
// ---------------------------------------------------------------------------

fn emit_section(bp: &SectionBlueprint, ind: usize) -> String {
  let mut out = String::new();
  let prefix = indent(ind);

  // Section opening line: section <type> [structural config only] {
  let section_type = bp.section_type.to_lowercase();
  let cfg = emit_structural_config(&bp.config);
  if cfg.is_empty() {
    out.push_str(&format!("{}section {} {{\n", prefix, section_type));
  } else {
    out.push_str(&format!("{}section {} {} {{\n", prefix, section_type, cfg));
  }

  let inner = ind + 1;

  match section_type.as_str() {
    "topbar" => emit_topbar_body(bp, inner, &mut out),
    "hero" => emit_hero_body(bp, inner, &mut out),
    "features" => emit_features_body(bp, inner, &mut out),
    "stats" => emit_stats_body(bp, inner, &mut out),
    "cta" => emit_cta_body(bp, inner, &mut out),
    "footer" => emit_footer_body(bp, inner, &mut out),
    _ => emit_generic_body(bp, inner, &mut out),
  }

  out.push_str(&format!("{}}}\n", prefix));
  out
}

// ---------------------------------------------------------------------------
// Section body emitters
// ---------------------------------------------------------------------------

fn emit_topbar_body(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  if let Some(brand) = bp.config.get("brand") {
    out.push_str(&format!("{}brand {}\n", pre, quoted(brand)));
  } else if let Some(ref t) = bp.title {
    out.push_str(&format!("{}brand {}\n", pre, quoted(t)));
  }

  if let Some(nav) = bp.config.get("nav") {
    out.push_str(&format!("{}nav {}\n", pre, quoted(nav)));
  }

  emit_cta_entries(bp, ind, out);

  for item in &bp.items {
    out.push_str(&emit_item(item, ind));
  }
}

fn emit_hero_body(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  if let Some(badge) = bp.config.get("badge") {
    out.push_str(&format!("{}badge {}\n", pre, quoted(badge)));
  }

  if let Some(ref title) = bp.title {
    if !title.is_empty() {
      out.push_str(&format!("{}title {}\n", pre, quoted(title)));
    }
  }
  if let Some(ref subtitle) = bp.subtitle {
    if !subtitle.is_empty() {
      out.push_str(&format!("{}subtitle {}\n", pre, quoted(subtitle)));
    }
  }

  emit_cta_entries(bp, ind, out);

  for item in &bp.items {
    out.push_str(&emit_item(item, ind));
  }
}

fn emit_features_body(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  // Skip section-level title/subtitle if they duplicate the first item's title
  let first_item_title = bp.items.first().map(|i| i.title.as_str()).unwrap_or("");
  let title_duplicates_first = bp.title.as_deref().map(|t| t == first_item_title).unwrap_or(false);

  if !title_duplicates_first {
    if let Some(ref title) = bp.title {
      if !title.is_empty() {
        out.push_str(&format!("{}title {}\n", pre, quoted(title)));
      }
    }
    if let Some(ref subtitle) = bp.subtitle {
      if !subtitle.is_empty() {
        out.push_str(&format!("{}subtitle {}\n", pre, quoted(subtitle)));
      }
    }
  }

  for item in &bp.items {
    out.push_str(&emit_item(item, ind));
  }
}

fn emit_stats_body(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  if let Some(ref title) = bp.title {
    if !title.is_empty() {
      out.push_str(&format!("{}title {}\n", pre, quoted(title)));
    }
  }

  for item in &bp.items {
    out.push_str(&emit_item(item, ind));
  }
}

fn emit_cta_body(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  if let Some(ref title) = bp.title {
    if !title.is_empty() {
      out.push_str(&format!("{}title {}\n", pre, quoted(title)));
    }
  }
  if let Some(ref subtitle) = bp.subtitle {
    if !subtitle.is_empty() {
      out.push_str(&format!("{}subtitle {}\n", pre, quoted(subtitle)));
    }
  }

  emit_cta_entries(bp, ind, out);

  for item in &bp.items {
    out.push_str(&emit_item(item, ind));
  }
}

fn emit_footer_body(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  if let Some(copyright) = bp.config.get("copyright") {
    out.push_str(&format!("{}copyright {}\n", pre, quoted(copyright)));
  }
  if let Some(nav) = bp.config.get("nav") {
    out.push_str(&format!("{}nav {}\n", pre, quoted(nav)));
  }

  for item in &bp.items {
    out.push_str(&emit_item(item, ind));
  }
}

fn emit_generic_body(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  if let Some(ref title) = bp.title {
    if !title.is_empty() {
      out.push_str(&format!("{}title {}\n", pre, quoted(title)));
    }
  }
  if let Some(ref subtitle) = bp.subtitle {
    if !subtitle.is_empty() {
      out.push_str(&format!("{}subtitle {}\n", pre, quoted(subtitle)));
    }
  }

  // Emit any well-known config fields the section might carry
  let known_section_fields = [
    "brand", "nav", "badge", "copyright", "footnote", "icon", "columns",
  ];
  for field in &known_section_fields {
    if let Some(val) = bp.config.get(*field) {
      out.push_str(&format!("{}{} {}\n", pre, field, quoted(val)));
    }
  }

  emit_cta_entries(bp, ind, out);

  for item in &bp.items {
    out.push_str(&emit_item(item, ind));
  }
}

// ---------------------------------------------------------------------------
// CTA helper — emits cta lines from config pairs
// ---------------------------------------------------------------------------

fn emit_cta_entries(bp: &SectionBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  // Primary CTA
  if let Some(text) = bp.config.get("cta_text") {
    let clean = clean_text(text);
    let link = bp.config.get("cta_link").map(|s| s.as_str()).unwrap_or("#");
    out.push_str(&format!(
      "{}cta {} -> {} primary\n",
      pre,
      quoted(&clean),
      quoted(link)
    ));
  }

  // Secondary CTA
  if let Some(text) = bp.config.get("cta2_text") {
    let clean = clean_text(text);
    let link = bp.config.get("cta2_link").map(|s| s.as_str()).unwrap_or("#");
    out.push_str(&format!(
      "{}cta {} -> {} secondary\n",
      pre,
      quoted(&clean),
      quoted(link)
    ));
  }

  // Additional CTAs (cta3_text, cta4_text, ...)
  let mut n = 3;
  loop {
    let key = format!("cta{}_text", n);
    if let Some(text) = bp.config.get(&key) {
      let clean = clean_text(text);
      let link_key = format!("cta{}_link", n);
      let link = bp.config.get(&link_key).map(|s| s.as_str()).unwrap_or("#");
      out.push_str(&format!(
        "{}cta {} -> {} secondary\n",
        pre,
        quoted(&clean),
        quoted(link)
      ));
      n += 1;
    } else {
      break;
    }
  }
}

// ---------------------------------------------------------------------------
// Item emitter — dispatches by item_type
// ---------------------------------------------------------------------------

fn emit_item(item: &ItemBlueprint, ind: usize) -> String {
  let item_type = item.item_type.to_lowercase();
  match item_type.as_str() {
    "item" => emit_item_block(item, ind),
    "line" => emit_simple_line("line", item, ind),
    "output" => emit_output_line(item, ind),
    "success" => emit_simple_line("success", item, ind),
    "prompt" => emit_prompt_line(item, ind),
    "chip" => emit_chip_line(item, ind),
    "code" => emit_simple_line("code", item, ind),
    "image" => emit_image_line(item, ind),
    "label" => emit_label_line(item, ind),
    "row" => emit_row_block(item, ind),
    "policy" => emit_policy_line(item, ind),
    "action" => emit_action_line(item, ind),
    "metric" => emit_metric_block(item, ind),
    _ => emit_item_block(item, ind), // fallback: treat as generic item
  }
}

// -- item "Title" -> "href"                     (link item)
// -- item "Title" icon:X { "description" ... }  (block item)
// -- item "Title"                                (simple item)
fn emit_item_block(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let mut out = String::new();

  // If item has href, emit as link item: item "Title" -> "href"
  if let Some(href) = item.config.get("href") {
    out.push_str(&format!("{}item {} -> {}\n", pre, quoted(&item.title), quoted(href)));
    return out;
  }

  // Config pairs excluding inner-only keys and href
  let inner_keys = ["price", "action", "meta", "action_icon", "price_interval", "href"];
  let mut inline_cfg: Vec<String> = Vec::new();
  let mut keys: Vec<&String> = item.config.keys()
    .filter(|k| !inner_keys.contains(&k.as_str()))
    .collect();
  keys.sort();
  for k in &keys {
    inline_cfg.push(format!("{}:{}", k, item.config[*k]));
  }
  let cfg_str = inline_cfg.join(" ");

  let has_desc = item.description.as_ref().map(|d| !d.is_empty()).unwrap_or(false);
  let has_inner = has_inner_config(item);
  let has_children = has_desc || has_inner;

  if has_children {
    if cfg_str.is_empty() {
      out.push_str(&format!("{}item {} {{\n", pre, quoted(&item.title)));
    } else {
      out.push_str(&format!("{}item {} {} {{\n", pre, quoted(&item.title), cfg_str));
    }
    let inner = ind + 1;
    let ipre = indent(inner);

    if let Some(ref desc) = item.description {
      if !desc.is_empty() {
        out.push_str(&format!("{}{}\n", ipre, quoted(desc)));
      }
    }

    // Emit inner config keys that represent child elements (price, action, meta)
    emit_item_inner_config(item, inner, &mut out);

    out.push_str(&format!("{}}}\n", pre));
  } else {
    // Single-line item
    if cfg_str.is_empty() {
      out.push_str(&format!("{}item {}\n", pre, quoted(&item.title)));
    } else {
      out.push_str(&format!("{}item {} {}\n", pre, quoted(&item.title), cfg_str));
    }
  }

  out
}

/// Checks if an item has inner config keys (price, action, meta) that need a block.
fn has_inner_config(item: &ItemBlueprint) -> bool {
  let inner_keys = ["price", "action", "meta", "action_icon", "price_interval"];
  item.config.keys().any(|k| inner_keys.contains(&k.as_str()))
}

/// Emits inner config entries (price, action, meta) inside an item block.
fn emit_item_inner_config(item: &ItemBlueprint, ind: usize, out: &mut String) {
  let pre = indent(ind);

  if let Some(price) = item.config.get("price") {
    let mut line = format!("{}price {}", pre, quoted(price));
    if let Some(interval) = item.config.get("price_interval") {
      line.push_str(&format!(" interval:{}", quoted(interval)));
    }
    line.push('\n');
    out.push_str(&line);
  }

  if let Some(action) = item.config.get("action") {
    let mut line = format!("{}action {}", pre, quoted(action));
    if let Some(icon) = item.config.get("action_icon") {
      line.push_str(&format!(" icon:{}", icon));
    }
    line.push('\n');
    out.push_str(&line);
  }

  if let Some(meta) = item.config.get("meta") {
    out.push_str(&format!("{}meta {}\n", pre, quoted(meta)));
  }
}

// -- line "$ command"
fn emit_simple_line(keyword: &str, item: &ItemBlueprint, ind: usize) -> String {
  format!("{}{} {}\n", indent(ind), keyword, quoted(&item.title))
}

// -- output "text" color:blue
fn emit_output_line(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let cfg = emit_config_pairs(&item.config);
  if cfg.is_empty() {
    format!("{}output {}\n", pre, quoted(&item.title))
  } else {
    format!("{}output {} {}\n", pre, quoted(&item.title), cfg)
  }
}

// -- prompt "question" answer:y
fn emit_prompt_line(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let cfg = emit_config_pairs(&item.config);
  if cfg.is_empty() {
    format!("{}prompt {}\n", pre, quoted(&item.title))
  } else {
    format!("{}prompt {} {}\n", pre, quoted(&item.title), cfg)
  }
}

// -- chip "text" icon:X
fn emit_chip_line(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let cfg = emit_config_pairs(&item.config);
  if cfg.is_empty() {
    format!("{}chip {}\n", pre, quoted(&item.title))
  } else {
    format!("{}chip {} {}\n", pre, quoted(&item.title), cfg)
  }
}

// -- image "alt" src:"url"
fn emit_image_line(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let cfg = emit_config_pairs(&item.config);
  if cfg.is_empty() {
    format!("{}image {}\n", pre, quoted(&item.title))
  } else {
    format!("{}image {} {}\n", pre, quoted(&item.title), cfg)
  }
}

// -- label "TEXT" style:mono
fn emit_label_line(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let cfg = emit_config_pairs(&item.config);
  if cfg.is_empty() {
    format!("{}label {}\n", pre, quoted(&item.title))
  } else {
    format!("{}label {} {}\n", pre, quoted(&item.title), cfg)
  }
}

// -- row "Label" { key "value" }
fn emit_row_block(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let mut out = format!("{}row {} {{\n", pre, quoted(&item.title));
  let inner = ind + 1;
  let ipre = indent(inner);

  // Emit each config pair as `key "value"` inside the row
  let mut keys: Vec<&String> = item.config.keys().collect();
  keys.sort();
  for k in keys {
    out.push_str(&format!("{}{} {}\n", ipre, k, quoted(&item.config[k])));
  }

  if let Some(ref desc) = item.description {
    if !desc.is_empty() {
      out.push_str(&format!("{}{}\n", ipre, quoted(desc)));
    }
  }

  out.push_str(&format!("{}}}\n", pre));
  out
}

// -- policy "Name" toggle:on
fn emit_policy_line(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let cfg = emit_config_pairs(&item.config);
  if cfg.is_empty() {
    format!("{}policy {}\n", pre, quoted(&item.title))
  } else {
    format!("{}policy {} {}\n", pre, quoted(&item.title), cfg)
  }
}

// -- action "Text" -> "/link" icon:add
fn emit_action_line(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let link = item.config.get("link").map(|s| s.as_str()).unwrap_or("#");

  // Collect config pairs excluding "link" (emitted in arrow syntax)
  let mut extra: HashMap<&String, &String> = item
    .config
    .iter()
    .filter(|(k, _)| k.as_str() != "link")
    .collect();

  let mut line = format!("{}action {} -> {}", pre, quoted(&item.title), quoted(link));

  // Append variant if present
  if let Some(variant) = extra.remove(&"variant".to_string()) {
    line.push_str(&format!(" {}", variant));
  }

  // Append remaining config pairs
  let mut ekeys: Vec<&&String> = extra.keys().collect();
  ekeys.sort();
  for k in ekeys {
    line.push_str(&format!(" {}:{}", k, extra[k]));
  }

  line.push('\n');
  line
}

// -- metric "Label" { "Value" }
fn emit_metric_block(item: &ItemBlueprint, ind: usize) -> String {
  let pre = indent(ind);
  let inner = ind + 1;
  let ipre = indent(inner);

  let mut out = format!("{}metric {} {{\n", pre, quoted(&item.title));

  if let Some(ref desc) = item.description {
    if !desc.is_empty() {
      out.push_str(&format!("{}{}\n", ipre, quoted(desc)));
    }
  }

  // Emit config inside metric block
  let mut keys: Vec<&String> = item.config.keys().collect();
  keys.sort();
  for k in keys {
    out.push_str(&format!("{}{} {}\n", ipre, k, quoted(&item.config[k])));
  }

  out.push_str(&format!("{}}}\n", pre));
  out
}
