#![allow(dead_code, unused_imports, unused_variables)]
//! Black Hole project orchestrator
//!
//! Chains all dump phases to absorb an entire project directory
//! and emit a single .cronus file describing the full stack.

use std::fs;
use std::path::{Path, PathBuf};
use serde_json::Value;

pub struct ProjectProfile {
    pub name: String,
    pub stack: String,
    pub src_dir: PathBuf,
    pub prisma_path: Option<PathBuf>,
    pub openapi_path: Option<PathBuf>,
    pub tailwind_path: Option<PathBuf>,
    pub env_path: Option<PathBuf>,
    pub ts_files: Vec<PathBuf>,
    pub port: u16,
}

/// Main entry: dump an entire project directory into .cronus
pub fn dump_project(dir: &Path) -> String {
    eprintln!(
        "\n  \x1b[36m⚡\x1b[0m Black Hole: absorbing {}...\n",
        dir.display()
    );

    // Phase 1: DETECT
    let profile = detect_project(dir);
    eprintln!("  Stack: {}", profile.stack);
    eprintln!("  Source files: {}", profile.ts_files.len());

    let mut entities_cronus = String::new();
    let mut routes_cronus = String::new();
    let mut auth_cronus = String::new();
    let mut style_cronus = String::new();

    // Phase 2: EXTRACT DATA LAYER
    // Try Prisma first (highest fidelity)
    if let Some(ref prisma_path) = profile.prisma_path {
        eprintln!(
            "  \x1b[32m✓\x1b[0m Prisma schema found: {}",
            prisma_path.display()
        );
        if let Ok(schema) = fs::read_to_string(prisma_path) {
            entities_cronus.push_str(&format!("# Entities from {}\n", prisma_path.display()));
            entities_cronus.push_str(&super::prisma::dump_prisma(&schema));
            entities_cronus = remove_app_block(&entities_cronus);
        }
    }

    // Try OpenAPI (high fidelity for routes)
    if let Some(ref openapi_path) = profile.openapi_path {
        eprintln!(
            "  \x1b[32m✓\x1b[0m OpenAPI spec found: {}",
            openapi_path.display()
        );
        if let Ok(json) = fs::read_to_string(openapi_path) {
            let dump = super::openapi::dump_openapi(&json);
            let dump_clean = remove_app_block(&dump);
            routes_cronus.push_str(&format!("# Routes from {}\n", openapi_path.display()));
            routes_cronus.push_str(&extract_api_blocks(&dump_clean));

            // Only add entities if Prisma didn't already provide them
            if entities_cronus.is_empty() {
                entities_cronus.push_str(&extract_entity_blocks(&dump_clean));
            }
        }
    }

    // TypeScript interface extraction (fallback if no Prisma/OpenAPI)
    if entities_cronus.is_empty() && !profile.ts_files.is_empty() {
        eprintln!("  \x1b[33m⚡\x1b[0m Scanning TypeScript interfaces...");
        let mut all_entities = Vec::new();
        for file in &profile.ts_files {
            if let Ok(source) = fs::read_to_string(file) {
                let extracted = super::typescript::extract_entities(&source);
                all_entities.extend(extracted);
            }
        }
        // Deduplicate by name
        let mut seen = std::collections::HashSet::new();
        all_entities.retain(|e| seen.insert(e.name.clone()));

        if !all_entities.is_empty() {
            eprintln!(
                "  \x1b[32m✓\x1b[0m Found {} entities from TypeScript",
                all_entities.len()
            );
            entities_cronus.push_str("# Entities extracted from TypeScript interfaces\n");
            entities_cronus.push_str(&super::typescript::emit_entities(&all_entities));
        }
    }

    // Phase 3: EXTRACT ROUTES (if OpenAPI didn't provide them)
    if routes_cronus.is_empty() {
        let detected = super::routes::detect_routes(&profile);
        if !detected.is_empty() {
            eprintln!(
                "  \x1b[32m✓\x1b[0m Detected {} routes",
                detected.len()
            );
            routes_cronus.push_str("# Routes detected from source code\n");
            routes_cronus.push_str(&super::routes::emit_routes(&detected));
        }
    }

    // Phase 4: EXTRACT STYLE
    if let Some(ref tw_path) = profile.tailwind_path {
        eprintln!("  \x1b[32m✓\x1b[0m Tailwind config found");
        if let Ok(config) = fs::read_to_string(tw_path) {
            style_cronus = super::style_extract::extract_style(&config, &profile.ts_files);
        }
    }

    // Phase 5: DETECT AUTH
    auth_cronus = detect_auth(&profile);

    // Phase 6: ASSEMBLE
    let mut output = String::new();

    // Header comment
    output.push_str(&format!("# Generated by: cronus dump {}\n", dir.display()));
    output.push_str(&format!("# Stack: {}\n\n", profile.stack));

    // App block
    output.push_str(&format!("app \"{}\" {{\n", profile.name));
    output.push_str("  stack react + tailwind\n");
    output.push_str(&format!("  port {}\n", profile.port));
    output.push_str("  database sqlite \"./data.db\"\n");
    output.push_str("  theme dark\n");
    output.push_str("}\n\n");

    // Auth
    if !auth_cronus.is_empty() {
        output.push_str(&auth_cronus);
        output.push('\n');
    }

    // Style
    if !style_cronus.is_empty() {
        output.push_str(&style_cronus);
        output.push('\n');
    }

    // Entities
    if !entities_cronus.is_empty() {
        output.push_str(&entities_cronus);
    }

    // Routes
    if !routes_cronus.is_empty() {
        output.push_str(&routes_cronus);
    }

    // Summary
    let entity_count = output.matches("entity ").count();
    let route_count = output.matches("  list ").count()
        + output.matches("  create ").count()
        + output.matches("  detail ").count()
        + output.matches("  update ").count()
        + output.matches("  delete ").count();
    eprintln!(
        "\n  \x1b[32m✓\x1b[0m Generated: {} entities, ~{} routes",
        entity_count, route_count
    );

    output
}

fn detect_project(dir: &Path) -> ProjectProfile {
    let mut profile = ProjectProfile {
        name: dir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string(),
        stack: "unknown".to_string(),
        src_dir: dir.to_path_buf(),
        prisma_path: None,
        openapi_path: None,
        tailwind_path: None,
        env_path: None,
        ts_files: Vec::new(),
        port: 3000,
    };

    // Read package.json
    let pkg_path = dir.join("package.json");
    if let Ok(content) = fs::read_to_string(&pkg_path) {
        if let Ok(pkg) = serde_json::from_str::<Value>(&content) {
            // Name
            if let Some(name) = pkg.get("name").and_then(|v| v.as_str()) {
                profile.name = name.to_string();
            }

            // Stack detection
            let deps_str = format!(
                "{}{}",
                pkg.get("dependencies").unwrap_or(&Value::Null),
                pkg.get("devDependencies").unwrap_or(&Value::Null)
            );

            if deps_str.contains("\"next\"") {
                profile.stack = "nextjs".to_string();
            } else if deps_str.contains("\"react\"") {
                profile.stack = "react".to_string();
            } else if deps_str.contains("\"vue\"") {
                profile.stack = "vue".to_string();
            } else if deps_str.contains("\"svelte\"") {
                profile.stack = "svelte".to_string();
            } else if deps_str.contains("\"elysia\"") {
                profile.stack = "elysia".to_string();
            } else if deps_str.contains("\"express\"") {
                profile.stack = "express".to_string();
            } else if deps_str.contains("\"@angular/core\"") {
                profile.stack = "angular".to_string();
            }

            // Port from scripts
            if let Some(scripts) = pkg.get("scripts").and_then(|v| v.as_object()) {
                if let Some(dev) = scripts.get("dev").and_then(|v| v.as_str()) {
                    if let Some(port_pos) = dev.find("--port ").or(dev.find("-p ")) {
                        let after = &dev[port_pos..];
                        let num_start = after.find(char::is_numeric).unwrap_or(0);
                        let num_str: String = after[num_start..]
                            .chars()
                            .take_while(|c| c.is_numeric())
                            .collect();
                        if let Ok(p) = num_str.parse::<u16>() {
                            profile.port = p;
                        }
                    }
                }
            }
        }
    }

    // Find Prisma schema
    for candidate in &[
        "prisma/schema.prisma",
        "schema.prisma",
        "db/schema.prisma",
    ] {
        let p = dir.join(candidate);
        if p.exists() {
            profile.prisma_path = Some(p);
            break;
        }
    }

    // Find OpenAPI
    for candidate in &[
        "openapi.json",
        "swagger.json",
        "api/openapi.json",
        "docs/openapi.json",
        "public/openapi.json",
    ] {
        let p = dir.join(candidate);
        if p.exists() {
            profile.openapi_path = Some(p);
            break;
        }
    }

    // Find Tailwind
    for candidate in &[
        "tailwind.config.ts",
        "tailwind.config.js",
        "tailwind.config.mjs",
        "tailwind.config.cjs",
    ] {
        let p = dir.join(candidate);
        if p.exists() {
            profile.tailwind_path = Some(p);
            break;
        }
    }

    // Find .env
    for candidate in &[".env.example", ".env.local", ".env"] {
        let p = dir.join(candidate);
        if p.exists() {
            profile.env_path = Some(p);
            break;
        }
    }

    // Collect TS/JS files (max 500)
    collect_ts_files(dir, &mut profile.ts_files, 0);
    profile.ts_files.truncate(500);

    profile
}

fn collect_ts_files(dir: &Path, files: &mut Vec<PathBuf>, depth: usize) {
    if depth > 10 || files.len() >= 500 {
        return;
    }

    let skip_dirs = [
        "node_modules",
        ".git",
        "target",
        "dist",
        ".next",
        "build",
        "__pycache__",
        ".cronus-build",
        ".vite",
        "coverage",
        ".turbo",
    ];

    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name().to_string_lossy().to_string();

            if path.is_dir() {
                if !skip_dirs.contains(&name.as_str()) && !name.starts_with('.') {
                    collect_ts_files(&path, files, depth + 1);
                }
            } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if matches!(ext, "ts" | "tsx" | "js" | "jsx") {
                    // Skip files > 100KB
                    if let Ok(meta) = fs::metadata(&path) {
                        if meta.len() <= 100_000 {
                            files.push(path);
                        }
                    }
                }
            }
        }
    }
}

fn detect_auth(profile: &ProjectProfile) -> String {
    // Check package.json deps for auth libraries
    let pkg_path = profile.src_dir.join("package.json");
    if let Ok(content) = fs::read_to_string(&pkg_path) {
        let has_auth = content.contains("next-auth")
            || content.contains("@auth/")
            || content.contains("passport")
            || content.contains("jsonwebtoken")
            || content.contains("bcrypt")
            || content.contains("argon2")
            || content.contains("lucia")
            || content.contains("clerk");

        if has_auth {
            return "auth {\n  entity User\n  login email + password\n  session jwt\n}\n"
                .to_string();
        }
    }

    // Check source files for auth patterns
    for file in profile.ts_files.iter().take(100) {
        if let Ok(source) = fs::read_to_string(file) {
            if source.contains("signIn")
                || source.contains("sign_in")
                || source.contains("login")
                || source.contains("authenticate")
                || source.contains("JWT")
                || source.contains("jwt")
            {
                return "auth {\n  entity User\n  login email + password\n  session jwt\n}\n"
                    .to_string();
            }
        }
    }

    String::new()
}

fn remove_app_block(cronus: &str) -> String {
    let mut result = String::new();
    let mut in_app_block = false;
    let mut brace_depth = 0;

    for line in cronus.lines() {
        if line.trim().starts_with("app ") || line.trim().starts_with("app \"") {
            in_app_block = true;
            brace_depth = 0;
        }

        if in_app_block {
            for ch in line.chars() {
                if ch == '{' {
                    brace_depth += 1;
                }
                if ch == '}' {
                    brace_depth -= 1;
                }
            }
            if brace_depth <= 0 && line.contains('}') {
                in_app_block = false;
            }
            continue;
        }

        result.push_str(line);
        result.push('\n');
    }

    result
}

fn extract_entity_blocks(cronus: &str) -> String {
    let mut result = String::new();
    let mut in_entity = false;
    let mut brace_depth = 0;

    for line in cronus.lines() {
        if line.trim().starts_with("entity ") {
            in_entity = true;
            brace_depth = 0;
        }

        if in_entity {
            result.push_str(line);
            result.push('\n');
            for ch in line.chars() {
                if ch == '{' {
                    brace_depth += 1;
                }
                if ch == '}' {
                    brace_depth -= 1;
                }
            }
            if brace_depth <= 0 && line.contains('}') {
                in_entity = false;
                result.push('\n');
            }
        }
    }

    result
}

fn extract_api_blocks(cronus: &str) -> String {
    let mut result = String::new();
    let mut in_api = false;
    let mut brace_depth = 0;

    for line in cronus.lines() {
        if line.trim().starts_with("api ") {
            in_api = true;
            brace_depth = 0;
        }

        if in_api {
            result.push_str(line);
            result.push('\n');
            for ch in line.chars() {
                if ch == '{' {
                    brace_depth += 1;
                }
                if ch == '}' {
                    brace_depth -= 1;
                }
            }
            if brace_depth <= 0 && line.contains('}') {
                in_api = false;
                result.push('\n');
            }
        }
    }

    result
}
