#![allow(dead_code, unused_imports, unused_variables)]
//! CRONUS Deploy Engine
//!
//! Generates deployment artifacts for a USER project (a directory of `*.cronus`
//! files): Dockerfile, docker-compose, .dockerignore, fly.toml, railway.json.
//! Images download the prebuilt `cronus` release binary pinned to the running
//! binary's version; they never need the kernel sources or a Rust toolchain.

use crate::cli::version::VERSION;

/// GitHub repository that publishes `cronus` release assets.
pub const RELEASE_REPO: &str = "pedrogbraz/cronus-kernel";

/// Linux target baked into container images (static musl binary: no glibc coupling).
pub const CONTAINER_TARGET: &str = "x86_64-unknown-linux-musl";

/// Directory inside the image holding persistent state (SQLite DB, `.cronus/`).
pub const DATA_DIR: &str = "/app/data";

/// Server command inside the image; the port comes from `$PORT`.
/// `--prod` disables internal routes, `--host 0.0.0.0` exposes the listener.
pub const RUN_COMMAND: &str = "cronus run --prod --host 0.0.0.0";

/// Release asset file name. Keep in sync with `.github/workflows/release.yml`
/// and `scripts/install.sh` (tests below check both).
pub fn release_asset_name(version: &str, target: &str) -> String {
    let ext = if target.ends_with("-windows-msvc") {
        "zip"
    } else {
        "tar.gz"
    };
    format!("cronus-{version}-{target}.{ext}")
}

pub fn release_asset_url(repo: &str, version: &str, target: &str) -> String {
    format!(
        "https://github.com/{repo}/releases/download/v{version}/{}",
        release_asset_name(version, target)
    )
}

const DOCKERFILE_BASE: &str = r##"# @TITLE@
# Generated by `cronus deploy`. The image downloads the prebuilt cronus @VERSION@
# binary from GitHub Releases and verifies its SHA256: no Rust toolchain and no
# kernel sources are needed. Pin another release with:
#   docker build --build-arg CRONUS_VERSION=x.y.z .

ARG CRONUS_VERSION=@VERSION@
ARG CRONUS_REPO=@REPO@

# ── Stage 1: fetch the release binary ──
FROM debian:bookworm-slim AS cronus
ARG CRONUS_VERSION
ARG CRONUS_REPO
ARG TARGETARCH
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates curl \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /tmp/cronus
RUN set -eu; \
    case "${TARGETARCH:-amd64}" in \
      amd64) target=@TARGET@ ;; \
      *) echo "cronus: no prebuilt linux/${TARGETARCH} binary; build with --platform linux/amd64" >&2; exit 1 ;; \
    esac; \
    version="${CRONUS_VERSION#v}"; \
    asset="cronus-${version}-${target}.tar.gz"; \
    base="https://github.com/${CRONUS_REPO}/releases/download/v${version}"; \
    curl -fsSLO "${base}/${asset}"; \
    curl -fsSLO "${base}/SHA256SUMS"; \
    awk -v a="${asset}" '$2 == a' SHA256SUMS > asset.sha256; \
    test -s asset.sha256; \
    sha256sum -c asset.sha256; \
    tar -xzf "${asset}"; \
    install -m 0755 "cronus-${version}-${target}/cronus" /usr/local/bin/cronus; \
    cronus --version

# ── Stage 2: runtime ──
FROM debian:bookworm-slim
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/* \
 && command -v setpriv >/dev/null \
 && groupadd --system --gid 10001 cronus \
 && useradd --system --uid 10001 --gid cronus --home-dir /app --no-create-home --shell /usr/sbin/nologin cronus \
 && mkdir -p /app/data/.cronus \
 && ln -s /app/data/.cronus /app/.cronus \
 && chown -R cronus:cronus /app
COPY --from=cronus /usr/local/bin/cronus /usr/local/bin/cronus
WORKDIR /app
"##;

const DOCKERFILE_PROJECT: &str = r##"
# Project sources and static assets (.dockerignore keeps local state and secrets out).
COPY --chown=cronus:cronus . /app/
"##;

const DOCKERFILE_RUNTIME: &str = r##"
# The SQLite database and runtime state (.cronus/ is symlinked here) must live
# on this volume: use `database sqlite "./data/app.db"` in the app block.
VOLUME ["/app/data"]
ENV PORT=@PORT@
EXPOSE @PORT@

# Volumes are often mounted root-owned (Fly, Railway). When started as root the
# entrypoint fixes /app/data ownership, then drops to the unprivileged `cronus`
# user (uid 10001) before exec'ing the server. `docker run --user 10001` skips it.
ENTRYPOINT ["/bin/sh", "-c", "set -eu; mkdir -p /app/data/.cronus; if [ \"$(id -u)\" = 0 ]; then chown -R cronus:cronus /app/data; exec setpriv --reuid=cronus --regid=cronus --init-groups \"$@\"; fi; exec \"$@\"", "cronus-entrypoint"]
CMD ["sh", "-c", "exec @RUN@ \"${PORT}\""]
"##;

fn one_line(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect()
}

fn render_dockerfile(title: &str, port: u16, project_section: &str) -> String {
    let template = format!("{DOCKERFILE_BASE}{project_section}{DOCKERFILE_RUNTIME}");
    template
        .replace("@TITLE@", &one_line(title))
        .replace("@VERSION@", VERSION)
        .replace("@REPO@", RELEASE_REPO)
        .replace("@TARGET@", CONTAINER_TARGET)
        .replace("@RUN@", RUN_COMMAND)
        .replace("@PORT@", &port.to_string())
}

/// Dockerfile for a user project: release binary + the project directory.
pub fn generate_dockerfile(app_name: &str, port: u16) -> String {
    render_dockerfile(
        &format!("{app_name} — CRONUS app image"),
        port,
        DOCKERFILE_PROJECT,
    )
}

/// Dockerfile with only the release binary; `.cronus` sources are mounted at
/// run time (microservices compose).
pub fn generate_service_dockerfile(port: u16) -> String {
    render_dockerfile("CRONUS service image", port, "")
}

/// Warning when the app's SQLite file would not land on the persistent volume.
pub fn database_outside_volume(db_path: Option<&str>) -> Option<String> {
    let raw = db_path.unwrap_or("data.db");
    let rel = raw.trim_start_matches("./");
    if rel.starts_with("data/") || raw.starts_with("/app/data/") {
        return None;
    }
    Some(format!(
        "database path \"{raw}\" is outside the persistent volume ({DATA_DIR}); \
         set `database sqlite \"./data/app.db\"` in the app block or the data is lost on redeploy"
    ))
}

pub fn generate_compose(app_name: &str, port: u16) -> String {
    let mut slug = slugify(app_name);
    if slug.is_empty() {
        slug = "cronus-app".into();
    }
    format!(
        r#"# {title} — docker compose
# Start with: docker compose up --build

services:
  app:
    build:
      context: .
      args:
        CRONUS_VERSION: "{VERSION}"
    container_name: {slug}
    ports:
      - "{port}:{port}"
    environment:
      PORT: "{port}"
      # Uncomment to pass a secret of at least 32 bytes from your shell; otherwise
      # one is generated and kept in the data volume (.cronus/jwt.key).
      # JWT_SECRET: "${{JWT_SECRET:?set JWT_SECRET}}"
    volumes:
      - cronus-data:{DATA_DIR}
    restart: unless-stopped

volumes:
  cronus-data:
"#,
        title = one_line(app_name),
    )
}

pub fn generate_dockerignore() -> &'static str {
    r#"# Keep local state, secrets and build output out of the image.
.git/
.gitignore
target/
node_modules/
data/
*.db
*.db-journal
*.db-wal
*.db-shm
.cronus/
.cronus-build/
.env
.env.*
"#
}

pub fn generate_ir(nodes: &[crate::parser::AstNode]) -> serde_json::Value {
    use crate::parser::AstNode;
    use serde_json::json;

    let mut app = json!(null);
    let mut entities = vec![];
    let mut pages = vec![];
    let mut apis = vec![];
    let mut services = vec![];
    let mut style = json!(null);

    for node in nodes {
        match node {
            AstNode::App(a) => {
                app = json!({
                    "name": a.name,
                    "port": a.port,
                    "stack": a.stack,
                    "database": a.database.as_ref().map(|d| json!({
                        "type": d.db_type,
                        "path": d.path,
                    })),
                });
            }
            AstNode::Entity(e) => {
                let fields: Vec<serde_json::Value> = e
                    .fields
                    .iter()
                    .map(|f| {
                        json!({
                            "name": f.name,
                            "type": format!("{:?}", f.field_type).to_lowercase(),
                            "required": f.required,
                            "unique": f.unique,
                            "enum_values": f.enum_values,
                        })
                    })
                    .collect();
                entities.push(json!({
                    "name": e.name,
                    "fields": fields,
                }));
            }
            AstNode::Page(p) => {
                let sections: Vec<serde_json::Value> = p
                    .sections
                    .iter()
                    .map(|s| {
                        json!({
                            "type": s.section_type,
                            "title": s.title,
                            "subtitle": s.subtitle,
                            "config": s.config,
                        })
                    })
                    .collect();
                pages.push(json!({
                    "route": p.route,
                    "type": p.page_type,
                    "entity": p.entity,
                    "title": p.title,
                    "sections": sections,
                }));
            }
            AstNode::Api(a) => {
                let routes: Vec<serde_json::Value> = a
                    .routes
                    .iter()
                    .map(|r| {
                        json!({
                            "name": r.name,
                            "method": format!("{:?}", r.method),
                            "path": format!("{}{}", a.prefix, r.path),
                            "auth": r.auth,
                        })
                    })
                    .collect();
                apis.extend(routes);
            }
            AstNode::Style(s) => {
                style = json!({
                    "theme": s.theme,
                    "accent": s.accent,
                    "radius": s.radius,
                    "font": s.font,
                });
            }
            AstNode::Service(s) => {
                services.push(json!({
                    "name": s.name,
                    "port": s.port,
                    "config": s.config,
                }));
            }
            _ => {}
        }
    }

    json!({
        "version": "0.2",
        "type": "abstract",
        "app": app,
        "entities": entities,
        "ui": pages,
        "api": apis,
        "services": services,
        "design": style,
        "meta": {
            "generatedAt": generate_timestamp(),
            "generator": concat!("cronus-kernel v", env!("CARGO_PKG_VERSION")),
        }
    })
}

fn generate_timestamp() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let s = secs % 60;
    let m = (secs / 60) % 60;
    let h = (secs / 3600) % 24;
    let days = secs / 86400;
    let y = 1970 + (days / 365);
    let rem = days % 365;
    let mo = rem / 30 + 1;
    let d = rem % 30 + 1;
    format!("{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z", y, mo, d, h, m, s)
}

fn slugify(name: &str) -> String {
    name.to_lowercase()
        .replace(' ', "-")
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-')
        .collect()
}

// ── Deploy Target Generators ──

pub fn generate_fly_toml(app_name: &str, port: u16) -> String {
    let slug = slugify(app_name);
    format!(
        r#"app = "{slug}"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "{port}"

[http_service]
  internal_port = {port}
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/api/health"
    timeout = "5s"

# SQLite database + .cronus/ state. Create once: fly volumes create cronus_data --size 1
[mounts]
  source = "cronus_data"
  destination = "{DATA_DIR}"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
"#
    )
}

/// Railway builds the Dockerfile and injects `PORT`; the image CMD reads it.
/// Attach a volume at `/app/data` in the Railway service settings.
pub fn generate_railway_config(_app_name: &str, _port: u16) -> String {
    r#"{
  "$schema": "https://railway.com/railway.schema.json",
  "build": { "builder": "DOCKERFILE", "dockerfilePath": "Dockerfile" },
  "deploy": {
    "healthcheckPath": "/api/health",
    "restartPolicyType": "ON_FAILURE"
  }
}
"#
    .to_string()
}

// ── Static Build ──

pub fn generate_static_build(pages_html: &[(String, String)]) -> Vec<(String, String)> {
    let script_nonce = crate::security::script_nonce_attr();
    let mut files: Vec<(String, String)> = Vec::new();
    let mut all_css = String::new();
    let mut all_js = String::new();

    for (route, html) in pages_html {
        // Extract route path → file path
        let path = if route == "/" || route.is_empty() {
            "dist/index.html".to_string()
        } else {
            let clean = route.trim_start_matches('/').trim_end_matches('/');
            format!("dist/{clean}/index.html")
        };

        // Extract <style> blocks into shared CSS
        let mut page_html = html.clone();
        let mut search_from = 0;
        while let Some(start) = page_html[search_from..].find("<style>") {
            let abs_start = search_from + start;
            if let Some(end) = page_html[abs_start..].find("</style>") {
                let abs_end = abs_start + end + "</style>".len();
                let style_block = &page_html[abs_start + "<style>".len()..abs_start + end];
                all_css.push_str(style_block);
                all_css.push('\n');
                page_html = format!("{}{}", &page_html[..abs_start], &page_html[abs_end..]);
            } else {
                search_from = abs_start + 1;
            }
        }

        // Extract <script{script_nonce}> blocks into shared JS
        search_from = 0;
        while let Some(start) = page_html[search_from..].find("<script>") {
            let abs_start = search_from + start;
            if let Some(end) = page_html[abs_start..].find("</script>") {
                let abs_end = abs_start + end + "</script>".len();
                let script_block = &page_html[abs_start + "<script>".len()..abs_start + end];
                all_js.push_str(script_block);
                all_js.push('\n');
                page_html = format!("{}{}", &page_html[..abs_start], &page_html[abs_end..]);
            } else {
                search_from = abs_start + 1;
            }
        }

        // Add CSS/JS links to <head>
        let final_html = if page_html.contains("</head>") {
            page_html.replacen(
                "</head>",
                r#"<link rel="stylesheet" href="/assets/cronus.css"><script src="/assets/cronus.js" defer></script></head>"#,
                1,
            )
        } else {
            format!(
                r#"<!DOCTYPE html><html><head><link rel="stylesheet" href="/assets/cronus.css"><script{script_nonce} src="/assets/cronus.js" defer></script></head><body>{page_html}</body></html>"#
            )
        };

        files.push((path, final_html));
    }

    files.push(("dist/assets/cronus.css".to_string(), all_css));
    files.push(("dist/assets/cronus.js".to_string(), all_js));

    files
}

// ── Health Endpoint ──

pub fn generate_health_endpoint(entity_count: usize, page_count: usize) -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let uptime = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();

    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"{{"status":"ok","version":"{version}","uptime":{uptime},"entities":{entity_count},"pages":{page_count}}}"#
    )
}

// ── Production Headers ──

pub fn generate_production_headers() -> Vec<(String, String)> {
    vec![
        ("X-Content-Type-Options".into(), "nosniff".into()),
        ("X-Frame-Options".into(), "DENY".into()),
        ("X-XSS-Protection".into(), "1; mode=block".into()),
        (
            "Strict-Transport-Security".into(),
            "max-age=31536000".into(),
        ),
        (
            "Content-Security-Policy".into(),
            "default-src 'self' 'unsafe-inline' 'unsafe-eval'".into(),
        ),
        ("Cache-Control".into(), "public, max-age=3600".into()),
    ]
}

// ── HTML Minification ──

pub fn minify_html(html: &str) -> String {
    let script_nonce = crate::security::script_nonce_attr();
    let mut result = String::with_capacity(html.len());
    let mut i = 0;
    let bytes = html.as_bytes();
    let len = bytes.len();

    while i < len {
        // Preserve <pre>, <script{script_nonce}>, <style> content verbatim
        if i + 5 < len {
            let tag_start = &html[i..];
            for preserve_tag in &["<pre", "<script", "<style"] {
                if tag_start.starts_with(preserve_tag) {
                    let close_tag = format!("</{}>", &preserve_tag[1..]);
                    if let Some(end) = html[i..].find(&close_tag) {
                        let block_end = i + end + close_tag.len();
                        result.push_str(&html[i..block_end]);
                        i = block_end;
                        continue;
                    }
                }
            }
        }

        // Remove HTML comments <!-- ... -->
        if i + 4 < len && &html[i..i + 4] == "<!--" {
            if let Some(end) = html[i..].find("-->") {
                i += end + 3;
                continue;
            }
        }

        // Collapse multiple whitespace into single space
        if bytes[i].is_ascii_whitespace() {
            // Skip all contiguous whitespace
            while i < len && bytes[i].is_ascii_whitespace() {
                i += 1;
            }
            // Only add space if we're not at start and not between > and <
            if !result.is_empty() && !result.ends_with('>') && i < len && bytes[i] != b'<' {
                result.push(' ');
            }
            continue;
        }

        result.push(bytes[i] as char);
        i += 1;
    }

    result
}

// ── Gzip Middleware Reference ──

pub fn generate_gzip_middleware_code() -> String {
    r#"// CRONUS Gzip Middleware — add to server response pipeline
// Requires: flate2 = "1.0" in Cargo.toml

use flate2::write::GzEncoder;
use flate2::Compression;
use std::io::Write;

fn gzip_response(body: &[u8], accept_encoding: &str) -> (Vec<u8>, Vec<(String, String)>) {
    if accept_encoding.contains("gzip") && body.len() > 1024 {
        let mut encoder = GzEncoder::new(Vec::new(), Compression::fast());
        encoder.write_all(body).unwrap_or_default();
        let compressed = encoder.finish().unwrap_or_default();
        if compressed.len() < body.len() {
            return (compressed, vec![
                ("Content-Encoding".into(), "gzip".into()),
                ("Vary".into(), "Accept-Encoding".into()),
            ]);
        }
    }
    (body.to_vec(), vec![])
}
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn run_args(port: &str) -> Vec<String> {
        std::iter::once("cronus")
            .chain(RUN_COMMAND.split_whitespace().skip(1))
            .chain(std::iter::once(port))
            .map(String::from)
            .collect()
    }

    #[test]
    fn release_asset_names_match_workflow_packaging() {
        assert_eq!(
            release_asset_name("1.2.3", "x86_64-unknown-linux-musl"),
            "cronus-1.2.3-x86_64-unknown-linux-musl.tar.gz"
        );
        assert_eq!(
            release_asset_name("1.2.3", "x86_64-pc-windows-msvc"),
            "cronus-1.2.3-x86_64-pc-windows-msvc.zip"
        );
        assert_eq!(
            release_asset_url("acme/cronus", "1.2.3", "aarch64-apple-darwin"),
            "https://github.com/acme/cronus/releases/download/v1.2.3/cronus-1.2.3-aarch64-apple-darwin.tar.gz"
        );
    }

    #[test]
    fn dockerfile_targets_user_project_not_kernel_repo() {
        let df = generate_dockerfile("My App", 8080);
        // Regression: the old Dockerfile compiled the kernel (`COPY src/` + cargo).
        assert!(!df.contains("COPY src/"));
        assert!(!df.contains("cargo build"));
        assert!(!df.contains("FROM rust"));

        assert!(df.starts_with("# My App — CRONUS app image\n"));
        assert!(df.contains(&format!("ARG CRONUS_VERSION={VERSION}\n")));
        assert!(df.contains(&format!("ARG CRONUS_REPO={RELEASE_REPO}\n")));
        assert!(df.contains(&format!("amd64) target={CONTAINER_TARGET} ;;")));
        assert!(df.contains("sha256sum -c asset.sha256"));
        assert!(df.contains("COPY --chown=cronus:cronus . /app/"));
        assert!(df.contains("useradd --system --uid 10001"));
        assert!(df.contains("exec setpriv --reuid=cronus --regid=cronus"));
        assert!(df.contains("VOLUME [\"/app/data\"]"));
        assert!(df.contains("ENV PORT=8080\n"));
        assert!(df.contains("EXPOSE 8080\n"));
        assert!(df.contains(
            "CMD [\"sh\", \"-c\", \"exec cronus run --prod --host 0.0.0.0 \\\"${PORT}\\\"\"]"
        ));
        assert!(!df.contains("@TITLE@") && !df.contains("@VERSION@") && !df.contains("@PORT@"));
        assert!(!df.contains("@RUN@") && !df.contains("@REPO@") && !df.contains("@TARGET@"));
    }

    #[test]
    fn dockerfile_asset_name_matches_release_asset_name() {
        let df = generate_dockerfile("x", 5175);
        let shell = "asset=\"cronus-${version}-${target}.tar.gz\"";
        assert!(df.contains(shell));
        let expanded = shell
            .trim_start_matches("asset=\"")
            .trim_end_matches('"')
            .replace("${version}", VERSION)
            .replace("${target}", CONTAINER_TARGET);
        assert_eq!(expanded, release_asset_name(VERSION, CONTAINER_TARGET));
        assert!(df.contains("releases/download/v${version}"));
    }

    #[test]
    fn dockerfile_title_cannot_inject_instructions() {
        let df = generate_dockerfile("evil\nRUN rm -rf /", 5175);
        assert!(!df.contains("\nRUN rm -rf /"));
    }

    #[test]
    fn container_run_command_uses_real_run_flags() {
        let args = run_args("8080");
        assert_eq!(
            crate::http_guard::run_mode_from(&args, None),
            crate::http_guard::RunMode::Production
        );
        assert_eq!(
            crate::http_guard::resolve_bind_ip(&args, None, false).unwrap(),
            std::net::IpAddr::from([0, 0, 0, 0])
        );
        // Port is positional (`cronus run [port]`); there is no `--port` flag.
        assert!(!RUN_COMMAND.contains("--port"));
    }

    #[test]
    fn service_dockerfile_has_binary_but_no_project_copy() {
        let df = generate_service_dockerfile(5220);
        assert!(df.contains("install -m 0755"));
        assert!(!df.contains("COPY --chown=cronus:cronus . /app/"));
        assert!(df.contains("ENV PORT=5220\n"));
    }

    #[test]
    fn fly_toml_mounts_data_volume_and_sets_port() {
        let toml = generate_fly_toml("My App", 8080);
        assert!(toml.starts_with("app = \"my-app\"\n"));
        assert!(toml.contains("internal_port = 8080\n"));
        assert!(toml.contains("PORT = \"8080\"\n"));
        assert!(toml.contains("destination = \"/app/data\"\n"));
        assert!(toml.contains("source = \"cronus_data\"\n"));
        assert!(toml.contains("path = \"/api/health\"\n"));
        assert!(!toml.contains("CRONUS_PORT"), "CRONUS_PORT is never read");
    }

    #[test]
    fn railway_config_is_json_and_uses_image_cmd() {
        let raw = generate_railway_config("x", 8080);
        let v: serde_json::Value = serde_json::from_str(&raw).expect("valid JSON");
        assert_eq!(v["build"]["builder"], "DOCKERFILE");
        assert!(v["deploy"].get("startCommand").is_none());
        assert_eq!(v["deploy"]["healthcheckPath"], "/api/health");
    }

    #[test]
    fn compose_pins_version_and_persists_data() {
        let yml = generate_compose("My App", 8080);
        assert!(yml.contains(&format!("CRONUS_VERSION: \"{VERSION}\"")));
        assert!(yml.contains("container_name: my-app\n"));
        assert!(yml.contains("- \"8080:8080\"\n"));
        assert!(yml.contains("PORT: \"8080\"\n"));
        assert!(yml.contains("- cronus-data:/app/data\n"));
        assert!(!yml.contains("CRONUS_PORT"));
        assert!(yml.contains("# JWT_SECRET: \"${JWT_SECRET:?set JWT_SECRET}\"\n"));
        assert!(generate_compose("!!!", 1).contains("container_name: cronus-app\n"));
    }

    #[test]
    fn dockerignore_keeps_state_and_secrets_out() {
        let ignore = generate_dockerignore();
        for entry in [".cronus/", "data/", "*.db", "*.db-wal", ".env", "target/"] {
            assert!(ignore.lines().any(|l| l == entry), "missing {entry}");
        }
    }

    #[test]
    fn database_volume_warning() {
        assert!(database_outside_volume(Some("./data/app.db")).is_none());
        assert!(database_outside_volume(Some("data/app.db")).is_none());
        assert!(database_outside_volume(Some("/app/data/app.db")).is_none());
        assert!(database_outside_volume(None).is_some());
        assert!(database_outside_volume(Some("./data.db")).is_some());
        assert!(database_outside_volume(Some("./database/app.db")).is_some());
    }

    #[cfg(unix)]
    fn installer_dry_run(envs: &[(&str, &str)]) -> std::process::Output {
        let script = concat!(env!("CARGO_MANIFEST_DIR"), "/scripts/install.sh");
        let mut cmd = std::process::Command::new("sh");
        cmd.arg(script)
            .env_clear()
            .env("PATH", std::env::var("PATH").unwrap_or_default())
            .env("HOME", "/home/tester")
            .env("CRONUS_INSTALL_DRY_RUN", "1");
        for (k, v) in envs {
            cmd.env(k, v);
        }
        cmd.output().expect("run sh scripts/install.sh")
    }

    #[cfg(unix)]
    #[test]
    fn install_script_dry_run_resolves_release_assets() {
        let cases = [
            ("Darwin", "arm64", "aarch64-apple-darwin"),
            ("Darwin", "x86_64", "x86_64-apple-darwin"),
            ("Linux", "x86_64", "x86_64-unknown-linux-musl"),
            ("Linux", "amd64", "x86_64-unknown-linux-musl"),
        ];
        for (os, arch, target) in cases {
            let out = installer_dry_run(&[
                ("CRONUS_OS", os),
                ("CRONUS_ARCH", arch),
                ("CRONUS_VERSION", "v1.2.3"),
                ("CRONUS_REPO", "acme/cronus"),
            ]);
            let stdout = String::from_utf8_lossy(&out.stdout);
            assert!(
                out.status.success(),
                "{os}/{arch}: {}",
                String::from_utf8_lossy(&out.stderr)
            );
            let url = release_asset_url("acme/cronus", "1.2.3", target);
            assert!(stdout.contains(&format!("asset_url={url}\n")), "{stdout}");
            assert!(stdout.contains(&format!("target={target}\n")), "{stdout}");
            assert!(stdout.contains(
                "checksums_url=https://github.com/acme/cronus/releases/download/v1.2.3/SHA256SUMS\n"
            ));
            assert!(stdout.contains("install_path=/home/tester/.cronus/bin/cronus\n"));
        }
    }

    #[cfg(unix)]
    #[test]
    fn install_script_dry_run_overrides_and_errors() {
        let out = installer_dry_run(&[
            ("CRONUS_TARGET", "x86_64-unknown-linux-gnu"),
            ("CRONUS_INSTALL_DIR", "/opt/tools"),
            ("CRONUS_VERSION", "0.9.0"),
        ]);
        let stdout = String::from_utf8_lossy(&out.stdout);
        assert!(out.status.success());
        let url = release_asset_url(RELEASE_REPO, "0.9.0", "x86_64-unknown-linux-gnu");
        assert!(stdout.contains(&format!("asset_url={url}\n")), "{stdout}");
        assert!(stdout.contains("install_path=/opt/tools/cronus\n"));

        let latest = installer_dry_run(&[("CRONUS_OS", "Linux"), ("CRONUS_ARCH", "x86_64")]);
        assert!(latest.status.success());
        assert!(String::from_utf8_lossy(&latest.stdout).contains("version=latest\n"));

        for (os, arch) in [
            ("Linux", "aarch64"),
            ("FreeBSD", "amd64"),
            ("MINGW64_NT-10.0", "x86_64"),
        ] {
            let out = installer_dry_run(&[("CRONUS_OS", os), ("CRONUS_ARCH", arch)]);
            assert!(!out.status.success(), "{os}/{arch} should fail");
            assert!(String::from_utf8_lossy(&out.stderr).contains("cronus-install: error:"));
            assert!(!String::from_utf8_lossy(&out.stdout).contains("asset_url="));
        }
    }
}
